### ISSUE TITLE
Installing ZettaKit via CocoaPods links to previous version

### ISSUE THREAD

**Issue by benpackard** [zettajs/ZettaKit#10]
The current release of ZettaKit is 0.03. However, installing via CocoaPods links against version 0.02. Not much of a CocoaPods pro, but I guess this is some kind of issue in the podspec?

Steps to reproduce:

Create a new Xcode project
Install ZettaKit via CocoaPods (`pod 'ZettaKit'`)
Open podfile.lock to review installed pod versions

Expected: ZettaKit 0.03
Actual: ZettaKit 0.02

Workaround: 
`pod 'ZettaKit', :git => 'https://github.com/zettajs/ZettaKit.git', :commit => '6f4f9a595c3e331901209df749db91de918818db'`

**Comment by mdobson** [comment]
Hey Ben

The latest hasn't been published. It's on my checklist for next week.

-Matt

**Comment by benpackard** [comment]
Oh that makes sense. I guess you can release on Github but there is some separate process for telling the CocoaPods master list which version to download.

I actually have a separate issue on its way against 0.3 which you might want to take a look at before publishing. I might need your advice on it next week, it's hard to nail down. I'll close this one.Thanks.
