### ISSUE TITLE
Provide log description or data in ZIKLogStreamEntry

### ISSUE THREAD

**Issue by benpackard** [zettajs/ZettaKit#15]
`ZIKLogStreamEntry` provides 4 properties:
- `topic` (string with device type / device UUID / stream name)
- `timestamp` (number)
- `transition` (string)
- `deviceState` (string)

This is sufficient to know the device, the transition's name, and the time of the transition, but not the new data. The end goal is to be able to produce something similar to the Zetta browser:

<img width="862" alt="screen shot 2016-02-19 at 3 18 35 pm" src="https://cloud.githubusercontent.com/assets/2280914/13187881/15012116-d71c-11e5-9bcd-ddf5d39fec47.png">

In this example, the message content ("Hello a third time") is not present in `ZIKLogStreamEntry`.

Sometimes there can be multiple fields updated in the transition - for example, see the iPhone device, which has an x, y, and z field for the `change` action. The values could be pre-arranged into a `description`, or a data dictionary could be provided.

**Comment by benpackard** [comment]
Paging @mdobson since I couldn't assign it.

**Comment by mdobson** [comment]
Expect this to be patched in the next ZettaKit drop sometime next week.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by mdobson** [comment]
This has been added and released.

**Comment by benpackard** [comment]
I'm finding that `ZIKLogStreamEntry.inputs` is always empty. Is there any particular device I should try this with?

**Comment by mdobson** [comment]
Taking a look now.

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!

**Comment by mdobson** [comment]
Apologies. This was a bug on my end. The proper term in the message was
_input_. I'll be dropping another SDK version tomorrow with this patched.

-Matt

_--_
_Matthew Dobson_ | _apigee https://apigee.com/_ | m: +1.734.634.5472 |
twitter @mdobs http://twitter.com/mdobs @apigee
https://twitter.com/apigee | _Apigee Community
http://community.apigee.com/_ for answers, ideas and support!
